services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    ports:
      - "7777:8000"
    networks:
      - myNetwork
    env_file:
      - .env

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"

  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

  booking_nginx_service:
    image: nginx
    container_name: booking_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - myNetwork
    depends_on:
      - booking_back_service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://booking_back:8000" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  myNetwork:
    external: true

# Вот здесь